version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: simtwo_backend
    ports:
      - "5000:5000"
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - simtwo-net
    environment:
      - FLASK_APP=backend.app
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - REDIS_HOST=simtwo_redis
      - REDIS_PORT=6379

  ws-server:
    build:
      context: ./ws-server
    container_name: simtwo_ws
    ports:
      - "8765:8765"
    depends_on:
      - backend
    networks:
      - simtwo-net

  redis:
    image: redis:latest
    container_name: simtwo_redis
    ports:
      - "6379:6379"
    networks:
      - simtwo-net

networks:
  simtwo-net:
    driver: bridge