app = "your-app-name"  # Replace with your Fly app name

primary_region = "ord"  # Choose closest region (ord = Chicago, you can change it)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"  # Match the port your app actually runs on

[[services]]
  internal_port = 5000  # Same here
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
