# fly.toml file for the Simtwo app
app = "simtwo"  # Replace with your Fly app name

primary_region = "ord"  # Chicago region (change it if needed)

[build]
  dockerfile = "Dockerfile"  # Reference to the Dockerfile

[env]
  PORT = "5000"  # Ensure the port your app listens to
  ENV = "prod"  # Set to 'prod' for production
  DOCKER_PASSWORD = "Victor9798!"  # Docker credentials
  DOCKER_USERNAME = "thekingkenya"
  FLASK_APP = "simtwo.backend.app.py"
  FLASK_ENV = "production"
  FLASK_RUN_HOST = "0.0.0.0"
  WEBHOOK_SECRET = "d9f1a3d47f83e25f92c97a912b3ac31c45ff98c87e2e98b03d78a12a78a813f5"
  LSTM_WEIGHT = "0.25"
  TRADING_AI_WEIGHT = "0.5"
  REINFORCEMENT_WEIGHT = "0.25"
  CONFIDENCE_THRESHOLD = "0.7"
  AI_AUTO_TRADE = "true"
  AUTO_TRADE_ENABLED = "true"
  AI_ACTIVE = "true"
  USE_VIRTUAL_ACCOUNT = "false"
  ORDER_TYPE = "market"
  DEFAULT_SYMBOL = "auto"
  MAX_OPEN_TRADES = "3"
  REFRESH_INTERVAL_SEC = "5"
  BITGET_API_KEY = "bg_1d7ea7c56644fb5da18a400c92a425d7"
  BITGET_SECRET_KEY = "e9121c2f6018c6844dd631a35583d4113fcfb1b2a8d3761c0ea430ea8fae7d13"
  BITGET_PASSPHRASE = "Victor9798"
  REDIS_URL = "redis://simtwo_redis:6379/0"
  PM2_PUBLIC_KEY = "ddwn8vexlp5c52f"
  PM2_SECRET_KEY = "wzpyspc0bq74exi"
  LOG_LEVEL = "info"
  VERBOSE = "0"
  FLY_API_TOKEN = "FlyV1 fm2_lJPECAAAAAAACHpaxBBcchQS7yEaY7NMcoQliSfOwrVodHRwczovL2FwaS5mbHkuaW8vdjGUAJLOAA8mqh8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDzQLtGON4z3Xd3jxYoqxbCWk2fPgyKWunKIeAGcCXoWBu/DQvtD4a2mISPhB1RJd1JHNkOs2sdO/obyONXETgTklMsNKT3+1tL3Ct44iKa9hD7nTH2UY8G9b2GWN1+/UxloqeBB5z9u7Od19dUS5sGsV7cWkB0HrthTlLI8hi6+bO0KwDNxNXEjqa9KB8QgVlMtfyb+TvQ53sMHzc6GdENR55yQghOvmB0yT2btiHo="

[[services]]
  internal_port = 5000  # Make sure this matches your app's listening port
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80  # Standard HTTP port

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443  # Standard HTTPS port
