name: Deploy to Railway (Docker)

on:
  push:
    branches:
      - main
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure Docker BuildKit and Mirror
        run: |
          echo '{
            "features": {
              "buildkit": true
            },
            "registry-mirrors": ["https://registry-1.docker.io"]
          }' > ~/.docker/config.json

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build -t registry.railway.app/simtwo:${{ github.sha }} .

      - name: Push Docker image to registry
        run: |
          docker push registry.railway.app/simtwo:${{ github.sha }}

      - name: Set up Node.js and run Railway Redeploy Script
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Railway Redeploy Script
        run: |
          echo "Running Railway Redeploy script..."
          npm install -g https
          node ./script.js ${{ secrets.RAILWAY_TOKEN }}

      - name: Log in to Railway CLI
        run: |
          npm install -g @railway/cli
          railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: |
          railway up --service=simtwo --detach