name: Deploy to Railway

on:
  push:
    branches:
      - main
      - release/*

jobs:
  setup:
    runs-on: ubuntu-22.04

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker (optional, since the GitHub runner typically has Docker pre-installed)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Railway (make sure your token is set as a secret in GitHub)
    - name: Log in to Railway
      run: |
        echo ${{ secrets.RAILWAY_TOKEN }} | railway login --token

    # Link your project (ensure you have the correct Railway project ID as a secret)
    - name: Link to Railway project
      run: railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}

    # Build and push the Docker image to Railway
    - name: Build Docker image
      run: |
        docker build -t railway-app .
    
    # Deploy the Docker container to Railway
    - name: Deploy to Railway
      run: |
        railway up --docker
