name: Deploy to Railway (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Railway using RAILWAY_TOKEN
        run: |
          npm install -g @railway/cli
          echo "//registry.npmjs.org/:_authToken=${{ secrets.RAILWAY_TOKEN }}" > ~/.npmrc
          railway config:use ${RAILWAY_TOKEN}
          railway link --project simtwoproject
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t registry.railway.app/simtwoproject:${{ github.sha }} .
          docker push registry.railway.app/simtwoproject:${{ github.sha }}

      - name: Deploy to Railway
        run: |
          railway up --service=simtwoproject --detach
