name: Deploy to Railway

on:
  push:
    branches:
      - main
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Node.js for running script.js
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    # Trigger Railway deployment using script.js
    - name: Trigger Railway Deployment
      run: node script.js ${{ secrets.RAILWAY_API_TOKEN }}
