name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js (using version 16.19.0 or other stable version)
    - name: Set up Node.js 16.19.0
      uses: actions/setup-node@v2
      with:
        node-version: '16.19.0'

    # Install Railway CLI using the custom GitHub action
    - name: Setup Railway CLI
      uses: MadeByThePinsHub/setup-railway-cli-action@v0.1.0
      with:
        npm-mode: false

    # Login to Railway using the token
    - name: Railway Login
      run: echo ${{ secrets.RAILWAY_TOKEN }} | railway login --token

    # Link the Railway project
    - name: Railway Link
      env:
        RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      run: railway link --project $RAILWAY_PROJECT_ID

    # Deploy to Railway
    - name: Deploy to Railway
      run: railway up
