name: Deploy to Railway

on:
  push:
    branches:
      - main  # Change to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (if necessary)
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust based on your application needs

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Railway Link
      env:
        RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}  # Store your Railway Project ID as a secret
      run: railway link --project $RAILWAY_PROJECT_ID  # Link the project using the project ID

    - name: Deploy to Railway
      run: railway up
