name: Deploy to Railway

on:
  push:
    branches:
      - main
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Node.js for running script.js
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Build Docker image and tag it
    - name: Build Docker image
      run: |
        docker build -t simtwo:latest .
    
    # Log in to Docker Hub (or your Docker registry if different)
    - name: Log in to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push the Docker image to the registry (Docker Hub or custom registry)
    - name: Push Docker image to registry
      run: |
        docker tag simtwo:latest ${{ secrets.DOCKER_USERNAME }}/simtwo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/simtwo:latest

    # Trigger Railway deployment using script.js
    - name: Trigger Railway Deployment
      run: node script.js ${{ secrets.RAILWAY_API_TOKEN }}
