name: Deploy to Railway (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Railway
        run: |
          npm install -g @railway/cli
          railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t registry.railway.app/simtwo:${{ github.sha }} .
          docker push registry.railway.app/simtwo:${{ github.sha }}

      - name: Deploy to Railway
        run: |
          railway up --service=simtwo --detach