name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Step 3: Log in using Railway Token and link to project
      - name: Link to Railway project
        run: |
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway link

      # Step 4: Deploy the project (if linked successfully)
      - name: Deploy to Railway
        run: railway up
