name: Deploy to Railway

on:
  push:
    branches:
      - main
      - release/*

jobs:
  setup:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.19.0'

    - name: Install dependencies
      run: npm install

    - name: Deploy to Railway
      run: |
        railway login --token ${{ secrets.RAILWAY_TOKEN }}
        railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}
        railway up
