name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v4

      # Step 2: Install the Fly CLI
      - name: Install Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Step 3: Deploy to Fly using the Fly API Token for authentication
      - name: Deploy App
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}  # GitHub secret that holds your Fly API token
        run: flyctl deploy --remote-only
